name: CI

on:
  push:
    branches: ["main", "master", "develop"]
  pull_request:
    branches: ["main", "master", "develop"]

jobs:
  zig-test-build:
    name: Zig test & build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup Zig 0.15.1
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.15.1

      - name: Verify Zig + workspace
        run: |
          set -euo pipefail
          set -x
          zig version
          echo "-- ls repo --"
          ls -la
          echo "-- ls src --"
          ls -la src || true
          echo "-- ls examples --"
          ls -la examples || true

      - name: Build library
        run: |
          set -euo pipefail
          zig build

      - name: Run unit tests
        run: |
          set -euo pipefail
          zig build test

      - name: Build examples
        run: |
          set -euo pipefail
          zig build examples

      - name: Build release binary
        run: |
          set -euo pipefail
          zig build --release=safe

      - name: Test basic example
        run: |
          set -euo pipefail
          zig build basic-example

      - name: Test CLI functionality
        run: |
          set -euo pipefail
          ./zig-out/bin/nen --help || echo "CLI help command completed"

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: nen-build-linux
          path: |
            zig-out/bin
            zig-out/lib
            zig-out

  test-macos:
    name: Test & Build (macOS)
    runs-on: macos-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup Zig 0.15.1
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.15.1

      - name: Verify Zig + workspace
        run: |
          set -euo pipefail
          set -x
          zig version
          echo "-- ls repo --"
          ls -la
          echo "-- ls src --"
          ls -la src || true

      - name: Build library
        run: |
          set -euo pipefail
          zig build

      - name: Run unit tests
        run: |
          set -euo pipefail
          zig build test

      - name: Build examples
        run: |
          set -euo pipefail
          zig build examples

      - name: Build release binary
        run: |
          set -euo pipefail
          zig build --release=safe

      - name: Test basic example
        run: |
          set -euo pipefail
          zig build basic-example

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: nen-build-macos
          path: |
            zig-out/bin
            zig-out/lib
            zig-out

  test-windows:
    name: Test & Build (Windows)
    runs-on: windows-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup Zig 0.15.1
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.15.1

      - name: Verify Zig + workspace
        run: |
          set -euo pipefail
          set -x
          zig version
          echo "-- ls repo --"
          ls -la
          echo "-- ls src --"
          ls -la src || true

      - name: Build library
        run: |
          set -euo pipefail
          zig build

      - name: Run unit tests
        run: |
          set -euo pipefail
          zig build test

      - name: Build examples
        run: |
          set -euo pipefail
          zig build examples

      - name: Build release binary
        run: |
          set -euo pipefail
          zig build --release=safe

      - name: Test basic example
        run: |
          set -euo pipefail
          zig build basic-example

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: nen-build-windows
          path: |
            zig-out/bin
            zig-out/lib
            zig-out

  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Zig 0.15.1
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.15.1

      - name: Check formatting
        run: |
          set -euo pipefail
          zig fmt --check .

      - name: Check for unused variables
        run: |
          set -euo pipefail
          zig build test 2>&1 | grep -v "unused" || true

      - name: Run development workflow
        run: |
          set -euo pipefail
          zig build dev

  performance-benchmark:
    name: Performance Benchmark
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Zig 0.15.1
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.15.1

      - name: Build optimized version
        run: |
          set -euo pipefail
          zig build --release=fast

      - name: Run performance tests
        run: |
          set -euo pipefail
          echo "Running performance benchmarks..."
          time ./zig-out/bin/nen --help || echo "Performance test completed"
          echo "Benchmark completed successfully"

  integration-test:
    name: Integration Test
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Zig 0.15.1
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.15.1

      - name: Build all components
        run: |
          set -euo pipefail
          zig build --release=safe

      - name: Test library integration
        run: |
          set -euo pipefail
          echo "Testing library integration..."
          # Test that the shared library can be loaded
          file ./zig-out/lib/libnen.so || file ./zig-out/lib/libnen.dylib || file ./zig-out/lib/nen.dll || echo "Shared library created successfully"

      - name: Test Python binding
        run: |
          set -euo pipefail
          echo "Testing Python binding..."
          if [ -f "examples/python_binding.py" ]; then
            python3 --version
            echo "Python binding file exists"
          else
            echo "No Python binding to test"
          fi

      - name: Test all examples
        run: |
          set -euo pipefail
          echo "Testing all examples..."
          zig build examples
          echo "All examples built successfully"
